# Generated by Django 5.2.8 on 2025-11-21 11:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('token_prefix', models.CharField(blank=True, default='', max_length=10)),
                ('daily_reset', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=False)),
                ('send_whatsapp', models.BooleanField(default=False)),
                ('send_push', models.BooleanField(default=False)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='myapp.companyinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_served', models.BooleanField(default=False)),
                ('is_skipped', models.BooleanField(default=False)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='myapp.companyinfo')),
            ],
        ),
    ]
